version: "3.3"
services:
  exchange-app:
    image: exchange-app
    environment:
      - FRONTEND_DIST_PATH=/usr/src/dist/public_html
      - EXCHANGERATES_API_KEY=__YOUR_API_KEY__
      - EXCHANGERATES_API_URL=http://api.exchangeratesapi.io/v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
    #   - redis
